### PR TITLE
Initial layout

### PR DESCRIPTION
**Pull request by tamsinrogers**
Initial layout files!  Not perfect but the spaces are blocked off for the most part.

To fix/add:
- header (with the search bar/etc) should probably be under the system banner, but I didn't have time to make it look right
- mule logo in the top left is stretched weird
- all the graph types are stored in the graphs.html file (in the template branch) - there should be three circle graphs at the top of the page and a line graph in the team overview part, the code's there they just don't show up

### CODE REVIEW

**Comment by benraivel** [comment]
The template looks pretty good to me

I removed the /layout folder because from what I could tell using diff it only had files already contained in /template. If that was incorrect we can revert.

Can't find the graphs.html file.

Also do you have any idea why only one of the charts is showing up?

**Comment by mlanicaputo** [comment]
> The template looks pretty good to me
> 
> I removed the /layout folder because from what I could tell using diff it only had files already contained in /template. If that was incorrect we can revert.
> 
> Can't find the graphs.html file.
> 
> Also do you have any idea why only one of the charts is showing up?

I couldn't tell why the other charts weren't showing up. Looks like the element they use is defined [here](https://github.com/benraivel/benraivel.github.io/blob/daec83f5907ec9e2de6104423c72945ae2cd0bbd/corona-free-dark-bootstrap-admin-template-1.0.0%202/template/assets/js/dashboard.js). Maybe we should modify that file to make it suit our needs more but I'm not sure.

**Comment by benraivel** [comment]
Fixed the charts, each id can only be used once so I just copied and pasted the js and used different ids. 

The line chart wasn't showing up because chart.js wasn't included in index.html

**Comment by benraivel** [comment]
@tamsinrogers how do you feel about removing the sidebar?

image

**Comment by tamsinrogers** [comment]
looks good to me, let's do it

**Pull request merged**
