### PR TITLE
Add capAthleteView.html

### PR DESCRIPTION
**Pull request by Calvin1581**
New html page for Coach/Admin/PEAK view of individual athletes

### CODE REVIEW

**Comment by mlanicaputo** [comment]
When I open the html file on my machine it shows up as unstyled HTML text; am I trippen or is that happening on your comp as well?

**Comment by Calvin1581** [comment]
It shows up like my screenshots in the main README for me, I don't know why it would look different. Is anyone else seeing this as Milo?

**Comment by benraivel** [comment]
The css/js isn't linked right I'm fixing it now

**Comment by benraivel** [comment]
looks good, merging now

**Pull request merged**
